pypro/aperitivos/urls.py
from django.urls import path

from pypro.aperitivos.views import video, indice

app_name = 'aperitivos'
urlpatterns = [
    path('', indice, name='indice'),
    path('<slug:slug>', video, name='video'),
]

pypro/base/urls.py
from django.urls import path

from pypro.base.views import home

app_name = 'base'
urlpatterns = [
    path('', home, name='home')
]

pypro/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from pypro.base.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pypro.base.urls')),
    path('aperitivos/', include('pypro.aperitivos.urls'))

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls))
    )

pypro/base/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_staff', True)

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """
    App base User class.
    Email and password are required. Other fields are optional.
    """

    first_name = models.CharField(_("first name"), max_length=150, blank=True)
    email = models.EmailField(_("email address"), unique=True)
    is_staff = models.BooleanField(
        _("staff status"),
        default=False,
        help_text=_("Designates whether the user can log into this admin site."),
    )
    is_active = models.BooleanField(
        _("active"),
        default=True,
        help_text=_(
            "Designates whether this user should be treated as active. "
            "Unselect this instead of deleting accounts."
        ),
    )
    date_joined = models.DateTimeField(_("date joined"), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = "email"
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _("user")
        verbose_name_plural = _("users")

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = "%s" % self.first_name
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        from django.core.mail import send_mail
        send_mail(subject, message, from_email, [self.email], **kwargs)

pypro/aperitivos/views.py
from django.shortcuts import render

# Create your views here.
from django.urls import reverse


class Video:
    def __init__(self, slug: str, titulo: str, youtube_id: str):
        self.slug = slug
        self.titulo = titulo
        self.youtube_id = youtube_id

    def get_absolute_url(self):
        return reverse('aperitivos:video', args=(self.slug,))


videos = [
    Video('motivacao', 'Video Aperitivo: Motivação', '2aYplgJrPDU'),
    Video('instalacao-windows', 'Instalação Windows', 'htg7WHSbR00')
]

video_dct = {v.slug: v for v in videos}


def video(request, slug):
    video = video_dct[slug]
    return render(request, 'aperitivos/video.html', context={'video': video})


def indice(request):
    return render(request, 'aperitivos/indice.html', context={'videos': videos})

pypro/base/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.


def home(request):
    return render(request, 'base/home.html')

pypro/aperitivos/templates/aperitivos/indice.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Pytron Pro - Aperitivos{% endblock title %}
{% block description %}Página com todos os vídeos gratuitos{% endblock description %}
{% block body %}
<div class="container">
    <div class="row mt-3">
        <div class="col-md-12">
            <h1 class="mt-3 mb-3">Lista de Vídeos Aperitivos</h1>
            <ol>
                {% for video in videos%}
                    <li><a href="{{ video.get_absolute_url }}">{{ video.titulo | default:"Faltando Título" }}</a></li>
                    {% empty %}
                    <p><span>Não foi encontrado nenhum vídeo de aperitivo</span></p>
                {% endfor %}
            </ol>
        </div>
    </div>
</div>
{% endblock body %}

<iframe width="560" height="315" src="https://www.youtube.com/embed/htg7WHSbR00" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

pypro/aperitivos/templates/aperitivos/video.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Pytron Pro - Aperitivo{% endblock title %}
{% block description %}Página com vídeo gratuito de Python{% endblock description %}
{% block body %}
<div class="container">
    <div class="row mt-3">
        <div class="col-md-12">
            <h1 class="mt-3 mb-3">{{ video.titulo | default:"Faltando Título"}}</h1>
            <iframe src="https://www.youtube.com/embed/{{ video.youtube_id }}"
                    title="YouTube video player"
                    width="560" height="315"
                    frameborder="0"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                    allowfullscreen>
            </iframe>

        </div>
    </div>
</div>
{% endblock body %}

<iframe width="560" height="315" src="https://www.youtube.com/embed/htg7WHSbR00" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

pypro/base/templates/base/base.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Python Pro{% endblock title %}</title>

    <meta name="description" content="{% block description %}Página do curso Python Pro{% endblock description %}">
    <meta name="author" content="Renato Damas">

    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}"/>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">


    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
    <a class="navbar-brand" href="{% url 'base:home' %}">Python Pro</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Dropdown
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>
{% block body %} {% endblock body %}

{% include 'base/footer.html' with contato_email='ramalho@python.pro.br' only %}

</body>
</html>

pypro/base/templates/base/footer.html
<footer class="main-footer mt-3 pt-4 text-light">
    <div class="container">
        <div class="row">
            <div class="col">
                <h4>Entre em contato</h4>
                <address>
                    <a href="tel:+5512997411854" class="text-light">+55 (12) 997-411-854</a>
                    <br/>
                    <a href="mailto:{{ contato_email}}" class="text-light">{{ contato_email}}</a>

                </address>
            </div>
        </div>
    </div>
    <div class="rights pt-1 pb-1">
        <div class="container">
            <div class="row">
                <div class="col">
                    {% now 'Y' %} Python Pro. Todos direitos reservados.

                </div>
            </div>
        </div>
    </div>
</footer>
<p class="alert-danger">Página desenvolvida apenas para fins de aprendizado.
    <br/>Não existe oferecimento real de qualquer curso.</p>

pypro/base/templates/base/home.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Python Pro - Home{% endblock title %}
{% block body %}
    <div class="container">
        <div class="row mt-3">
            <div class="col-md-12">
                <div class="jumbotron">
                    <h2>
                        Curso de Python com Luciona Ramalho
                    </h2>
                    <h4 class="mt-3">Matrículas abertas, custo R$ 1.000,00</h4>
                    <!-- INICIO DO BOTAO PAGSEGURO -->
                    <a href="https://pag.ae/7XeQ-KNuo/button" target="_blank"
                       title="Pagar com PagSeguro"><img
                            src="//assets.pagseguro.com.br/ps-integration-assets/botoes/pagamentos/205x30-pagar.gif"
                            alt="Pague com PagSeguro - é rápido, grátis e seguro!"/></a>
                    <!-- FIM DO BOTAO PAGSEGURO -->

                    <h4 class="mt-3">Entre na lista de espera</h4>
                    <!-- Begin Mailchimp Signup Form -->
                    <div id="mc_embed_signup">
                        <form action="https://herokuapp.us6.list-manage.com/subscribe/post?u=ee0bb7477a3432c7e6d2b3026&amp;id=a784513548"
                              method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form"
                              class="validate" target="_blank" novalidate>
                            <div class="form-row align-items-center" id="mc_embed_signup_scroll">
                                <div class="col-sm-4 my-1">
                                    <label class="sr-only" for="mce-EMAIL">Email <span class="asterisk">*</span>
                                    </label>
                                    <input type="email" value="" name="EMAIL" class="form-control requerid"
                                           id="mce-EMAIL"
                                           placeholder="exemplo@email.com">
                                </div>
                                <div class="col-sm-3 my-1">
                                    <label class="sr-only" for="mce-FNAME">Nome </label>
                                    <input type="text" value="" name="FNAME" class="form-control" id="mce-FNAME"
                                           placeholder="Seu nome">
                                </div>
                                <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                                <div style="position: absolute; left: -5000px;" aria-hidden="true">
                                    <input type="text"
                                           name="b_ee0bb7477a3432c7e6d2b3026_a784513548"
                                           tabindex="-1"
                                           value=""></div>

                                <div class="col-auto my-1">
                                    <input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe"
                                           class="btn btn-primary">
                                </div>
                                <div id="mce-responses" class="col-auto">
                                    <div class="response" id="mce-error-response" style="display:none"></div>
                                    <div class="response" id="mce-success-response" style="display:none"></div>
                                </div>

                            </div>
                        </form>
                    </div>
                    <script type='text/javascript'
                            src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script>
                    <script type='text/javascript'>(function ($) {
                        window.fnames = new Array();
                        window.ftypes = new Array();
                        fnames[0] = 'EMAIL';
                        ftypes[0] = 'email';
                        fnames[1] = 'FNAME';
                        ftypes[1] = 'text';
                        fnames[4] = 'PHONE';
                        ftypes[4] = 'phone';
                    }(jQuery));
                    var $mcj = jQuery.noConflict(true);</script>
                    <!--End mc_embed_signup-->
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <h5 class="card-header">
                                Mais detalhes sobre o instrutor
                            </h5>
                            <div class="card-body">
                                <p class="card-text">
                                    <img class="img-thumbnail float-left mr-3"
                                         src="{% static 'img/luciano-ramalho.png' %}"
                                         alt="Foto de Lucinano Ramalho">
                                    Luciano Ramalho é programador Python desde 1998, Fellow da Python Software
                                    Foundation; é
                                    sócio do <a href="https://python.pro.br">Python.pro.br</a> – uma empresa de
                                    treinamento
                                    – e cofundador do Garoa Hacker
                                    Clube, o primeiro hackerspace do Brasil. Ele é o autor do livro do livro <a
                                        href="https://www.amazon.com.br/s?k=python+fluente+luciano+ramalho"
                                        target="_blank">Python
                                    Fluente</a>. Tem liderado equipes de desenvolvimento de
                                    software e ministrado cursos sobre Python em empresas de mídia, bancos e para o
                                    governo
                                    federal.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}